### ISSUE TITLE
Particle Distribution issues

### ISSUE THREAD

**Issue by gzhao2014** [D3DEnergetic/nstx-fidasim#4]
@lstagner 

 (1). When I use SPIRAL fast ion, the obtained spectra seems to have bigger noise than the case using TRANSP fast ion. If I need to increase the particle numbers in the inputs setting?? The note can be found by following link.

https://docs.google.com/document/d/1K954Kj8x71XUO7eSyoddT2JxQXD-TMbEO5ic0reoVWg/edit?usp=sharing

 (2). When we plot the integrated signal in the interested wavelength region, I think we should have to smooth the spectral before doing the integration?

**Comment by lstagner** [comment]
Since you are using a particle distribution and not a density function like TRANSP/NUBEAM you need to make sure that you have sampled phase space thoroughly. This means that your SPIRAL distributions needs to have a lot of particles to be representative of the distribution. Looking at your input it seems like the number of SPIRAL particles should be sufficient, although I would redo the SPIRAL run to output 10 times as many just to see if it actually matters.

You could also adjust `n_fast` to be larger so that it will launch the mc particle at more torodial/gyro-angles. The relationship between the number of torodial/gyro-angles is given by `nphi/n_gyro = ceil(n_fast/n_particles)` where `n_particles` is the number of SPIRAL particles

**Comment by gzhao2014** [comment]
@lstagner 

It seems that I didn't find the parameter 'n_fast' ?  is 'n_fast'  the 'ntotal'  in read_spiral.pro or the 'n_fida' in nstx_prefida.pro?

**Comment by lstagner** [comment]
You can change it in the *_inputs.dat file that prefida generates

**Comment by gzhao2014** [comment]
I still don't find 'n_fast' ?  Do you mean change 'n_fida'?

**Comment by lstagner** [comment]
Yes

**Comment by gzhao2014** [comment]
Thanks

**Comment by gzhao2014** [comment]
@lstagner 
After increase n_fida from 5E6 to 5e8, the obtained spectra became smooth. It is shown in last page of the following file
https://docs.google.com/document/d/1K954Kj8x71XUO7eSyoddT2JxQXD-TMbEO5ic0reoVWg/edit?usp=sharing

Do I need to increase n_fida value?

**Comment by lstagner** [comment]
If you want. The best thing to do is to see how the radial profile changes as you increase `n_fida` Once it stops changing significantly then thats the number you use.

FYI. You can just drag and drop images directly into the comments. No need to use google docs

**Comment by gzhao2014** [comment]
@lstagner 

When I set n_fida=5E8. The spectra seems much better.
![qq 20160501001103](https://cloud.githubusercontent.com/assets/15125494/14940030/c0e4fc18-0f30-11e6-8f7e-9f3c305bc47d.png)

I have more two questions
1. If I need to calculate the passive_fida signal? and use the 'active_fida' minus 'passive_fida' to get net signal? I am not sure if the present calculation is the net fida signal? 

2.However, I'd like to know, where can I find the IDL routine to plot the integrated signal (profile of fida signal along the major radius) ?  If not, I also can write a sample routine to plot it?

**Comment by gzhao2014** [comment]
@lstagner 

The obtained FIDA profile from nubeam and spiral, are different(fig.1). Here, the equilibrium file is the same.
In addition, based on the fast ion distribution information of SPIRAL, the 'spiral' FIDASIM results seems not make sence. If you have some idea to figure out this problem?

![image](https://cloud.githubusercontent.com/assets/15125494/14957360/f06be104-1052-11e6-89ee-d7e66da1c882.png)
Fig.1

Following figure is fast ion distribution from SPIRAL. Based on this. I think the expected spectra should peaks at ~110cm:
![image](https://cloud.githubusercontent.com/assets/15125494/14957494/a2c03f94-1053-11e6-8b32-1c11d133eb58.png)
Fig.2

**Comment by lstagner** [comment]
There are a few things you should check.
1. Make sure you have the `btipsign` correct
2. Check the energy bounds and make sure they are the same. 
3. Check the pitch bounds as well
4. Make sure the distributions you are comparing are actually equivalent.

**Comment by gzhao2014** [comment]
the Monte Carlo samples from 'get_fbm' don't include the phi(toroidal angle) information. Could I just set phi=0 for all of the sample? Or need to set a random value for the phi of individual samples?

**Comment by lstagner** [comment]
We assume torodial symmetry so you could set phi to "banana" for all I care.

Also you shouldn't have to modify the output from get_fbm.
Read_MC_nubeam.pro can read the file.

the Monte Carlo samples from 'get_fbm' don't include the phi(toroidal
angle) information. Could I just set phi=0 for all of the sample? Or need
to set a random value for the phi of individual samples?

**Comment by gzhao2014** [comment]
Ok. However, I just already made a change on  IDL routine, which reads

/p/nstxusr/nstx-users/ghao/CODE/FIDASIM/NSTX_ROUTINES/src/read_fbm_spiral.pro

**Comment by gzhao2014** [comment]
![test](https://cloud.githubusercontent.com/assets/15125494/15015292/0735fbae-11d9-11e6-8f88-7c35c9f0d818.PNG)
red curve: NUBEAM_fast_ion_function, 
blue curve: NUBEAM_MC,    the toroidal angle for each fast ion is random in the region [-180,180]
     During dumping the particles I limit the energy is in [10, 90]KeV, and use the guiding center position of particle. The dumped particles # is 620000.   The dump MC file is saved in 
/p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/142296A02_DATA2_NUBEAM_SPIRAL_FORMAT_2.TXT

@lstagner 
Yes. I found the dumped fast ion samples are wrong! Just corrected it, and restart FIDASIM.

**Comment by bgrierson21** [comment]
The toroidal angle should only matter for prompt losses.  I don't understand why you would need the toroidal angle for the fast-ion distribution function unless you're comparing with a measurement that is able to sample on the fast-ion toroidal transit frequency.  Measurements such as FIDA only need the toroidal angle information for the diagnostic line of sight relative to a beam in the machine coordinates.  Forgive me for interrupting this conversation, but it seems that there may be a misunderstanding at play here.

**Comment by gzhao2014** [comment]
@bgrierson21 

Yes. I think You are right. Since FIDASIM assumes the particles are toroidal symmetric( pls see Luke's comments), hence the setting of the initial toroidal angle of fast ion will not give  useful information for FIDASIM.  Here, I set the toroidal angle , only to avoid the complain from IDL routine during read the fast ion distribution. This set doesn't have physical reason.

**Comment by lstagner** [comment]
I will take a look at the code and rerun my test case (after I make the required updates to the d3d routines). 

But I have a suspicion that you didn't prepare the distribution correctly. I would of expected that the NUBEAM MC distribution would differ from the the NUBEAM distribution function in a similar was as the SPIRAL distribution differed if there was a systematic problem with the code. This results suggests a different cause.

**Comment by lstagner** [comment]
I did my benchmark and everything looks fine. There is a small difference but nothing like what you got above.

![screenshot from 2016-05-05 03-03-59](https://cloud.githubusercontent.com/assets/4305891/15041084/27f9362c-126e-11e6-9614-a5550e72ae4b.png)

![screenshot from 2016-05-05 03-01-04](https://cloud.githubusercontent.com/assets/4305891/15041090/31b92c08-126e-11e6-944f-8013d8068dda.png)

**Comment by gzhao2014** [comment]
![22](https://cloud.githubusercontent.com/assets/15125494/15051171/51985dee-12c5-11e6-85a6-bfc1d08ac7a0.PNG)
red: NUBEAM_fast_ion_function, 
blue: NUBEAM_MC,
Different panel denotes different channels

![45](https://cloud.githubusercontent.com/assets/15125494/15051271/bec8feaa-12c5-11e6-8c85-2d643bd670aa.PNG)
red: NUBEAM_fast_ion_function, 
blue: NUBEAM_MC,
R=126.9cm

![ss](https://cloud.githubusercontent.com/assets/15125494/15051226/7f89d034-12c5-11e6-920f-3f0407f1321a.PNG)
The net signal. 

IT seems that there still have difference between the MC and function methods for NSTX. Maybe somewhere is still wrong in my inputs setting.

**Comment by lstagner** [comment]
Well that looks a bit better. It is now consistent with the SPIRAL distribution. Most likely you are reading the file incorrectly. Are you using `lib/read_mc_nubeam.pro` like I mentioned. It is what I used in my benchmark so you should use it as well. Likewise you should use the `lib/read_spira.pro` if you are not using it already.

I have [updated](https://github.com/D3DEnergetic/nstx-fidasim/commit/313062a0142722f5ea1f2b06ef5fcecf4755fb74) the nstx routines to allow for that type of distribution so it should be easy to use the right routine.

Also FYI, When you edit a comment we don't get a email notification of the edit; we only get notified for the initial comment. If your editing to change the formatting you can just use the Preview button to see what your comment will look like before you submit. 

EDIT: If I'm right you wont get notified of this edit

**Comment by gzhao2014** [comment]
@lstagner 
Thanks, I will find time to test again. It seems that  "npts=long(parts[w[0]+1])" in read_mc_nubeam.pro should be
npts=long(parts[w[0]+2])

**Comment by lstagner** [comment]
Ok this is getting ridiculous. Send me both the mc nubeam file and the spiral file you are trying to use. Unless they have changed the formats of the files you should not be having this much trouble.

**Comment by gzhao2014** [comment]
Don't worry, When I make the minor change in read_mc_nubeam. It works well. I dump the particles using get_fbm, and doen't make any change in the generated file. An example is saved in 

/p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/142296A00_DATA1_NUBEAM_SPIRAL_FORMAT.TXT

/p/nstxusr/nstx-users/ghao/CODE/FIDASIM/lib/read_mc_nubeam.pro
/p/nstxusr/nstx-users/ghao/CODE/FIDASIM/lib/read_spiral.pro

In addition, I found there is no fidasim in /p/fida/fidasim/. Hence,  compile it again(21:00, 05/05/2016)

**Comment by lstagner** [comment]
OK I corrected `read_mc_nubeam.pro` to handle the problem (It was Bills fault). I didn't use your fix since it was specific to that file. 

The only thing I can think of that would cause the difference is the number of MC particles. I used 5_000_000 particles in my benchmark. In your files you only use ~600_000.

**Comment by gzhao2014** [comment]
During create the inputs files, it displays the following information 

the Beam grid rotation angles that would align it with the beam centerline
    alpha =  -0.0000000000
    beta =   0.0000000000

If alpha and beta should have a finite value? 

At present, I try to test a NUBEAM_MC case with 5_000_000.

**Comment by lstagner** [comment]
Don't worry about those it just means the beam grid is aligned with the
beam sight line.

**Comment by gzhao2014** [comment]
For MC method, I use read_mc_nubeam to read the dumped particles from NUBEAM, and particles number = 5_000_000. Red curve in the following figure.（Note: for comparison, the amplitude are rescaled）
And compared with the result using function method, as shown by blue curve.
It seems there still have a big discrepancy between these two method. I wonder if there is an issue in the geometry of NSTX， when use MC method??  

![7taj z b3i e48f9 2na 7](https://cloud.githubusercontent.com/assets/15125494/15092912/7ee8d3d8-1445-11e6-8d48-735f626e7f87.png)
![fxq 8 860ma or9hbww26](https://cloud.githubusercontent.com/assets/15125494/15092851/fb2b3028-1443-11e6-9a51-efbeb0d15293.png)

**Comment by lstagner** [comment]
Try using the opposite `btipsign` it may give us hints to what is going on.

**Comment by gzhao2014** [comment]
Just for reference, the below figure is for the case of SPIRAL_MC, using different btipsign. For NUBEAM_MC, I will restart the calculation using btipsign=1.

![rv3tk7 w6o_d 07qqbk4x d](https://cloud.githubusercontent.com/assets/15125494/15093877/f013e4b4-1461-11e6-8f7d-ef7c4f0cf372.png)
![99](https://cloud.githubusercontent.com/assets/15125494/15094013/a6b8bade-1465-11e6-9536-e6f1e7aaf185.png)

**Comment by gzhao2014** [comment]
@lstagner 
For the case of NUBEAM_MC, comparison between BTIP=-1(red curve in the figure) and BTIP=1(blue curve in figure). Number of fast ions 5_000_000.

![999999](https://cloud.githubusercontent.com/assets/15125494/15095718/6b6c2746-14a5-11e6-9f48-f7dcfdffd5fd.png)

![00000](https://cloud.githubusercontent.com/assets/15125494/15095719/6ff5fd64-14a5-11e6-9761-6b17f90b9609.png)

**Comment by lstagner** [comment]
OK. Also make sure you have `Ntotal` set to the same value as the nubeam
distribution. You have to do this so that the Halo density is the same in
both cases. This also makes it so you don't have to normalize the FIDA
spectra.

**Comment by gzhao2014** [comment]
Does  `Ntotal` effect the simulated FIDA profile?

**Comment by lstagner** [comment]
Yes. It affects the DCX/Halo neutrals which in turn affects the FIDA
signal. The relevant code can be found [here](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L5767)

**Comment by gzhao2014** [comment]
OK。However, where could I get 'Ntotal' value used by NUBEAM distribution function method?

在 2016-05-10 06:25:29，"Luke Stagner" notifications@github.com 写道：

> Yes. It affects the DCX/Halo neutrals which in turn affects the FIDA
> signal. The relevant code can be found [here](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L5767)
>

**Comment by lstagner** [comment]
It can be found in the nubeam distribution file under the variable `ntot_d_nbi`. Note this `Ntotal` is calculated by integrating over all of phase space so make sure that mc nubeam distribution has the same energy/pitch bounds as the nubeam distribution.

**Comment by lstagner** [comment]
You should try to reproduce my benchmark case (/p/fida/lstagner/MCFIDASIM/BENCHMARK) Check out the README file I included for instructions. You should also try extracting the same MC distribution and compare against mine to make sure you are using get_fbm correctly.

**Comment by gzhao2014** [comment]
Thanks.  Do you use the script to to get MC from TRANSP as follows : /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/get_fbm_spiral.scr
 How could I know your used options during use get_fbm? (I guess, during use get_fbm, I used the wrong option)

**Comment by lstagner** [comment]
The following commands should exactly recreate the distribution I used. 

```
get_fbm
159243H06
/p/fida/lstagner/MCFIDASIM/BENCHMARK
q
9
T
D3D
1
W
C
Y
15
5000000
Y
1.947550E+04
,
Y
Y
Y
Y
mc_159243H06_9
q
q
q
```

This will create the file `mc_159243H06_9` which is identical to the version I used (aside from a few superficial differences)

**Comment by lstagner** [comment]
You should also use the neutrals from the nubeam run to separate errors caused by differences is the halo and beam deposition. You do this by changing the neutrals file in the `inputs.dat` and changing the `load_neutrals` switch

**Comment by gzhao2014** [comment]
Ok. First I will to try NSTX case again. A stupid question: How do you get the particles number over 20KeV for the FBM case? For example:  20 keV = 2.3564223e+18 . Make the integration in (R, Z) based on the .cdf file?

**Comment by lstagner** [comment]
```
IDL> a = read_ncdf("./159243H06_fi_9.cdf")
% Compiled module: READ_NCDF.
% Loaded DLM: NCDF.
IDL> print,string(a.hint)
dN = f*bmvol*de*da/2
IDL> energy = a.e_d_nbi
IDL> pitch = a.a_d_nbi
IDL> dE = abs(energy[1] - energy[0])
IDL> dp = abs(pitch[1] - pitch[0])
IDL> bmvol = a.bmvol
IDL> f = a.f_d_nbi
IDL> print,a.ntot_d_nbi
   3.5720911e+18
IDL> help,total(total(total(f,1),1)*bmvol)*dE*dp/2
<Expression>    DOUBLE    =    3.5720911e+18
IDL> w=where(energy ge 20000)
IDL> help,total(total(total(f[w,*,*,*],1),1)*bmvol)*dE*dp/2
<Expression>    DOUBLE    =    2.3564221e+18
```

**Comment by lstagner** [comment]
Any progress on this?

**Comment by gzhao2014** [comment]
Thanks for your routine to identify the particle # in the chosen energy region. The submitted job is still on queue. Hence, no progress yet.

**Comment by lstagner** [comment]
@gzhao2014 I took a look at the queue and it looks like the FIDASIM jobs you have running are taking way longer than usual. How did you submit the job? FIDASIM may be trying to use more cores then it was allocated so its stalling out. Using [`submit_fidasim`](http://d3denergetic.github.io/FIDASIM/page/01_getting_started/03_running.html#submitting-to-a-sge-cluster-using-submit_fidasim) should prevent that from happening.

**Comment by gzhao2014** [comment]
when I try to use submit_fidasim in debug mode, it tells us maybe there are some parameters need to be reset in submit_fidasim.

At present, I qsub my jobs again. I think this time it should be ok. 

$> submit_fidasim -db /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/142296A00_DATA1.002500.1A.NUBEAM_FBM_1E6_inputs.dat

#!/bin/tcsh
#PBS -N fidasim
#PBS -l nodes=1:ppn=4
#PBS -l mem=2048mb
#PBS -l walltime=5:00:00
#PBS -r n
#PBS -V
#PBS -o /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/142296A00.out
#PBS -e /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/142296A00.err

echo " "
echo "-------------------"
echo "This is a $PBS_ENVIRONMENT job"
echo "This job was submitted to the queue: $PBS_QUEUE"
echo "The job's id is: $PBS_JOBID"
echo "-------------------"
echo "The master node of this job is: $PBS_O_HOST"

set NPROCS=`wc -l < $PBS_NODEFILE`

set NNODES=`uniq $PBS_NODEFILE | wc -l`

echo "This job is using $NPROCS CPU(s) on the following $NNODES node(s):"
echo "-----------------------"
uniq $PBS_NODEFILE | sort
echo "-----------------------"

echo -n 'Started job at : ' ; date

/p/nstxusr/nstx-users/ghao/CODE/FIDASIM_code_2015/fidasim /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/142296A00_DATA1.002500.1A.NUBEAM_FBM_1E6_inputs.dat

echo -n 'Ended job at  : ' ; date
echo " "

exit

**Comment by gzhao2014** [comment]
For the D3D benchmark case, I think the two methods can obtain the similar spectrum profile, which is same with that you have obtained.

In following figure, red curve: distribution function;  blue curve : MC

![6666](https://cloud.githubusercontent.com/assets/15125494/15327943/35a8c4e2-1c21-11e6-85d2-bbc2ddefbdc3.PNG)

**Comment by gzhao2014** [comment]
@lstagner For D3D case, In the spectra.h5 file, it seems that there are three Radius values corresponding to one view channel. When plot the FIDA profile, which Radius value should be used? 

f='particle_spectra.h5'
x=read_hdf5(f)
print,x.RADIUS.DATA

x.Radius.DATA
       170.70572       170.84299       171.01097       175.03387       174.88813       175.54943       180.48623       180.54752
       181.17638     ........

**Comment by lstagner** [comment]
Use the indices 1,4,7,... (0-based indexing)

**Comment by gzhao2014** [comment]
![777](https://cloud.githubusercontent.com/assets/15125494/15335458/68536324-1c40-11e6-8c84-597176500fe9.PNG)
I think it is same with that Luke has obtained.[Use the RADIUS indices 1,4,7,... (0-based indexing)]

**Comment by gzhao2014** [comment]
@lstagner 
When I used the same energy/pitch boundary and the same ntotal, the results still have difference. Today, You say pat attention to some place where will read TRANSP equilibrium? I'd like to know how to check that? During creating the 'inputs'  files? 

![99999](https://cloud.githubusercontent.com/assets/15125494/15344920/bd390514-1c78-11e6-8dbf-e8095f9e79ed.png) Integration in wavelength

**Comment by lstagner** [comment]
You should do two things.
1. The Monte Carlo distributions also need to estimate the fast ion density. This in turn affects the neutral population. You should run the MC run using the neutrals from the FBM run. That way we can narrow in on where things are going wrong.
2. Use the [extract_transp_geqdsk](http://d3denergetic.github.io/FIDASIM/page/01_getting_started/02_preprocess.html#extracting-geqdsk-file-and-plasma-parameters-from-transp) routine to extract the geqdsk file that TRANSP is using when creating the MC distribution. This will eliminate the equilibrium as a source of error.

**Comment by gzhao2014** [comment]
For the first suggestion. Based on my understanding,(I am not sure is it right) 
 I need  to set   load_neutrals:1  in nstx_prefida.pro
 and copy FBM neutrals.h5  to MC_id_neutrals.h5

Another questions: for the case of load_neutrals:0, and using MC method. How does code create neutrals.h5 file? 

sorry so many basic question.

**Comment by lstagner** [comment]
You do not have to regenerate the input files. All you need to do is change the `neutrals_file` and the `load_neutrals` variables in the `*_inputs.dat` file. 

If `load_neutrals` is set to zero and the `neutrals_file` doesn't exist then FIDASIM calculates the neutrals.

**Comment by lstagner** [comment]
I just pushed changes that removes the FIDASIM debugging switches (like `load_neutrals`) from the PREFIDA inputs structure. Before this change I could see how it could be confusing since we don't specify the `neutrals_file` in the PREFIDA inputs even though you could set `load_neutrals` equal to one. This is strange since this is telling FIDASIM to use a neutrals file that doesn't exist yet.

**Comment by gzhao2014** [comment]
1. For MC method, it seems that reading the neutrals from FBM method does't decrease the discrepancy.
   `
2. (a)Try to extract g-file from TRANSP, using following commends
   
   extract_transp_geqdsk /p/transparch/result/NSTX/10 142296A00 -d NSTX -t 0.25 -bt -1
   
   (b) generated gfile is stored in 
   /p/nstxusr/nstx-users/ghao/FIDASIM_RESULTS/NSTX/142296_2016/test/g142296.00250_000_extract_TRANSP

(c) it seems there is a complain from read_geqdsk 

```
% Tag name TIME is undefined for structure <Anonymous>.
% Execution halted at: READ_GEQDSK       154 /p/fida/FIDASIM/lib/read_geqdsk.pro
```

Do we need to update some routines?

**Comment by lstagner** [comment]
No. I literally just ran the exact code and it works with your gfile

```
IDL> igrid = rz_grid(100.0,240.d0,70,-100.d0,100.d0,100) 
% Compiled module: RZ_GRID.
IDL> a=read_geqdsk('/u/lstagner/g142296.00250',igrid,g=g)
% Compiled module: READ_GEQDSK.
% Compiled module: READG.
% Compiled module: EFIT_READ.
% Compiled module: EFIT_FILENAME_PARSE.
% Compiled module: ISNUMBER.
% Compiled module: NWRDS.
% Compiled module: DELCHR.
  *** dividing time from file by 1000 ***
  >>> in READG_FILE, reading info.file /u/lstagner/g142296.00250
% Type conversion error: Unable to convert given STRING to Long.
% Detected at: READG_FILE        461 /u/lstagner/FIDASIM/deps/efit/readg.pro
% Compiled module: STR_SEP.
% Type conversion error: Unable to convert given STRING to Long.
% Detected at: READG_FILE        662 /u/lstagner/FIDASIM/deps/efit/readg.pro
% Type conversion error: Unable to convert given STRING to Long.
% Detected at: READG_FILE        662 /u/lstagner/FIDASIM/deps/efit/readg.pro
% Type conversion error: Unable to convert given STRING to Long.
% Detected at: READG_FILE        662 /u/lstagner/FIDASIM/deps/efit/readg.pro
% Compiled module: DT_NICENUMBER.
% Compiled module: NINT.
% Compiled module: RHO_RZ.
% Compiled module: LINSPACE.
% Compiled module: FLUXMAP.
% Compiled module: SPLINE.
% Compiled module: QSIMPV.
% Compiled module: CONTOUR_PSI.
% Compiled module: METRIC.
% Compiled module: DERIV.
IDL> help,a
** Structure <18d83c28>, 9 tags, length=350024, data length=350024, refs=1:
   TIME            DOUBLE          0.25000000
   DATA_SOURCE     STRING    '/u/lstagner/g142296.00250'
   MASK            INT       Array[70, 100]
   BR              DOUBLE    Array[70, 100]
   BT              DOUBLE    Array[70, 100]
   BZ              DOUBLE    Array[70, 100]
   ER              DOUBLE    Array[70, 100]
   ET              DOUBLE    Array[70, 100]
   EZ              DOUBLE    Array[70, 100]
```

**Comment by gzhao2014** [comment]
Yes. Your are right. There is a typo in my file name, when run nstx_inputs. The results can come tomorrow morning

**Comment by gzhao2014** [comment]
A short show about the new calculation.

It seems that the g-file can change FIDA profile for MC method. However, MC case have a inside shift for using TRANSP-gfile. Maybe, something is still wrong. At present , I wish to increase n_fida one order to check if the profile will have change. 

![22222](https://cloud.githubusercontent.com/assets/15125494/15444518/a6e24d68-1ebf-11e6-9656-8f379c33bb75.PNG)
![4444](https://cloud.githubusercontent.com/assets/15125494/15444519/a82e4ed8-1ebf-11e6-924d-d09bf8111407.PNG)

**Comment by lstagner** [comment]
Increasing n_fida wont change anything. Just make sure you are using the
same equilibrium in the FBM case as well.

**Comment by gzhao2014** [comment]
Yes. Both method uses the same g-file(extract from TRANSP output)

I'd like to make some more explanation about the procedure I did:
1. prepare the inputs files  for 'nb_1a', 'nb_1b' and 'nb_1c', respectively
2.  run for three sources, respectivlly
3. finally sum the FIDA signal over all of sources
4. make integration(in wavelength space) in the chosen wavelength region.
   
   Note:  I made the following modification during run FIDASIM: 
         In nstx_prefida.pro. I　changed 'nbi_source=nxtx_beams('nb_1b')' to 
                            'nbi_source=nstx_beams(inputs.beam)'
        Do this will affect the results?

**Comment by lstagner** [comment]
I tried out a simplified version of your case and I now think that what you are seeing is real. I'm looking into what could be causing the issue.

**Comment by lstagner** [comment]
All fixed now. It was actually a problem with the old FIDA calculation. Basically I used the fast-ion density at the particle location instead of the gyro center. This created an implicit dependence on the gyro-radius. Usually the gyro-radius is small enough that this isn't an issue.

There is also a small thing I found while debugging this issue. Specifically `get_fbm` can sometimes be different from what `read_nubeam.pro` would suggest. I am not sure if this is a bug in `get_fbm` or a interpolation error in `read_nubeam.pro`. To test whether this could cause a large error I generated my own samples. 

![nstx_distribution](https://cloud.githubusercontent.com/assets/4305891/15468742/bca8e8fa-209a-11e6-997d-b857e6316422.png)
![radial_profile](https://cloud.githubusercontent.com/assets/4305891/15468938/f0871f6a-209b-11e6-96b6-c489ebf3e0da.png)

As you can see it doesn't have a large effect.

@gzhao2014 In response to your last comment. You should use the same beam grid for all three beams. This makes it easy to compare the beam deposition.

**Comment by gzhao2014** [comment]
Many Thanks. Your result looks nice. 

Based on my understanding, you have updated the fidasim.f90 source file and read_nubeam.pro routine. Does this modification on source file also affect the result MC method? 
1. Is "read_fbm.pro" the old version of read_nubeam.pro?
1. Use the same beam grid: does it mean I should keep 'nbi_source=nxtx_beams('nb_1b')' in  nstx_prefida.pro.?

**Comment by lstagner** [comment]
1. No modifications to the MC fida routines were necessary 
2. `read_fbm` is sleep talk for `get_fbm`
3. `nbi_source` isn't in the `nstx_prefida.pro` source code so I cant be sure.

FYI All the files I used for debugging can be found in `/p/fida/lstagner/GZH`

**Comment by gzhao2014** [comment]
Another question, when make the integration to get FIDA along major radius. What's your chosen wavelength region?

**Comment by lstagner** [comment]
I was lazy and just used the full region.

**Comment by gzhao2014** [comment]
Ok. I see. In your calculation, Are all of the sources(1a, 1b, 1c) included?

**Comment by lstagner** [comment]
No, just 1B
